volumes:
  mariadb-data: { }

services:

  mariadb:
    image: mariadb:lts-ubi9
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_DATABASE: flightsdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 9080:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: dbpassword
    restart: unless-stopped
    depends_on:
      - mariadb